spring:
  datasource:
    username: academic_admin
    password: Admin123@
    url: "jdbc:postgresql://localhost:5432/academic"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
